n_z = 25
batch_size = 64

input_shape = (64,64)

DATASET_NAME = "dataset.hdf5"
DATASET_DB_NAME = "training"

INSPECT_DATASET = False

LEARNING_RATE = 0.001

MAX_NUMBERS_EMBEDDING = 16384

VIDEO_INTERVALL = 20
CHECKPOINT_INTERVALL = 10
LATENT_INTERVALL = 1
RECONSTRUCTION_INTERVALL = 1
